/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dataset } from './dataset';
import { DataService } from './dataService';


export interface Catalog { 
    '@id'?: string;
    '@type'?: string;
    dataset?: Array<Dataset>;
    service?: Array<DataService>;
    participantId?: string;
    '@context'?: Array<string>;
}

