/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CelExpression { 
    leftOperand?: string;
    description?: string;
    expression?: string;
    scopes?: Set<string>;
    '@context'?: Array<string>;
    '@type'?: string;
    '@id'?: string;
}

