/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Contract { 
    id?: string;
    counterParty?: string;
    type?: string;
    agreementId?: string;
    assetId?: string;
    signingDate?: string;
    consumer?: string;
    provider?: string;
    policy?: { [key: string]: object; };
    pending?: boolean;
}

