/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractOffer } from './contractOffer';


export interface ContractNegotiation { 
    id?: string;
    state?: string;
    correlationId?: string;
    counterPartyId?: string;
    counterPartyAddress?: string;
    protocol?: string;
    participantContextId?: string;
    type?: string;
    contractAgreementId?: string;
    contractOffers?: Array<ContractOffer>;
}

