/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataspaceInfo { 
    dataspaceId?: number;
    agreementTypes?: Array<string>;
    roles?: Array<string>;
    id?: number;
}

