/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataService } from './dataService';


export interface Distribution { 
    '@type'?: string;
    format?: string;
    accessService?: DataService;
}

