/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileResource { 
    fileId?: string;
    fileName?: string;
    contentType?: string;
    uploadDateIso?: string;
    metadata?: { [key: string]: object; };
}

