/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewDataspaceInfo } from './newDataspaceInfo';


/**
 * Tenant registration details
 */
export interface NewTenantRegistration { 
    tenantName?: string;
    dataspaceInfos?: Array<NewDataspaceInfo>;
}

