/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataspaceInfo } from './dataspaceInfo';
import { VPAResource } from './vPAResource';


export interface ParticipantResource { 
    id?: number;
    identifier?: string;
    agents?: Array<VPAResource>;
    dataspaceInfos?: Array<DataspaceInfo>;
}

