/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataspaceInfo } from './dataspaceInfo';
import { VirtualParticipantAgent } from './virtualParticipantAgent';


export interface Participant { 
    id?: number;
    identifier?: string;
    agents?: Array<VirtualParticipantAgent>;
    dataspaceInfos?: Array<DataspaceInfo>;
}

