/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Constraint } from './constraint';


export interface Prohibition { 
    '@type'?: string;
    action?: string;
    constraint?: Array<Constraint>;
}

