/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Participant } from './participant';


export interface Tenant { 
    id?: number;
    providerId?: number;
    name?: string;
    participants?: Array<Participant>;
    properties?: { [key: string]: object; };
}

