/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantResource } from './participantResource';


export interface TenantResource { 
    id?: number;
    providerId?: number;
    name?: string;
    participants?: Array<ParticipantResource>;
}

