/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataspaceInfo } from './dataspaceInfo';


export interface TenantRegistration { 
    tenantName?: string;
    dataspaceInfos?: Array<DataspaceInfo>;
    properties?: { [key: string]: object; };
}

