/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferProcessRequest { 
    counterPartyId?: string;
    contractId?: string;
    dataDestination?: { [key: string]: object; };
    transferType?: string;
}

