/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferProcess { 
    type?: string;
    protocol?: string;
    correlationId?: string;
    counterPartyAddress?: string;
    dataDestination?: { [key: string]: object; };
    assetId?: string;
    contractId?: string;
    contentDataAddress?: { [key: string]: object; };
    privateProperties?: { [key: string]: object; };
    transferType?: string;
    dataPlaneId?: string;
    dataplaneMetadata?: { [key: string]: object; };
    state?: string;
    stateTimestamp?: number;
}

