/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VirtualParticipantAgent { 
    id?: number;
    type?: VirtualParticipantAgent.TypeEnum;
    state?: VirtualParticipantAgent.StateEnum;
}
export namespace VirtualParticipantAgent {
    export const TypeEnum = {
        ControlPlane: 'CONTROL_PLANE',
        CredentialService: 'CREDENTIAL_SERVICE',
        DataPlane: 'DATA_PLANE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StateEnum = {
        Initial: 'INITIAL',
        Pending: 'PENDING',
        Active: 'ACTIVE',
        Disposing: 'DISPOSING',
        Disposed: 'DISPOSED',
        Locked: 'LOCKED',
        Offline: 'OFFLINE',
        Error: 'ERROR'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


